apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "devcentral.name" . }}
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.fedco-devcentral-app: semver:~1.1
  labels:
    {{- include "fedco-devcentral-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fedco-devcentral-app.labels" . | nindent 6 }}
  template:
    metadata:
      name: fedco-devcentral-app
      labels:
        {{- include "fedco-devcentral-app.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "devcentral.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: {{ .Values.service.port }}
        livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.service.port }}
        readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.service.port }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - name: config-js-volume
            mountPath: /app/build/config.js
            subPath: config.js
      volumes:
        - name: config-js-volume
          configMap:
            name: {{ .Values.configMap.name }}


